# Don't print a new line at the start of the prompt
add_newline = true
command_timeout = 1000
scan_timeout = 50

# emojis=("ğŸŒ¿" "ğŸ€" "ğŸŒ±" "ğŸƒ" "ğŸ‚")
# EMOJI=${emojis[$RANDOM % ${#emojis[@]} ]}

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "ğŸª  â¯"
vicmd_symbol = "ğŸª  [V](bold green)"
error_symbol = "ğŸª  [â¯](bold red)"
# success_symbol = "â¯"
# vicmd_symbol = "[V](bold green)"
# error_symbol = "[â¯](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false
symbol = "ï£– "

[hostname]
ssh_only = true
format =  "on [$hostname](bold red) "
trim_at = "."
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = " [$user]($style): "
disabled = false
show_always = true

[git_branch]
symbol = "ğŸŒ±  "

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[ruby]
disabled = true

[aws]
disabled = true

